### ISSUE TITLE
SSD FDP

### ISSUE THREAD

**Issue by arnenator** [Tietgen-ITU/research-project#11]
We want to get to know how SSDs with FDP works as best as possible. For that reason we need to investigate further:
### Tasks
- [ ] Tietgen-ITU/advanced-data-systems#12
- [ ] Tietgen-ITU/advanced-data-systems#13
- [ ] Tietgen-ITU/advanced-data-systems#11 
- [ ] Tietgen-ITU/advanced-data-systems#14
