### ISSUE TITLE
Finalize report

### ISSUE THREAD

**Issue by arnenator** [Tietgen-ITU/research-project#31]
We need to finish the report. For that reason here is a todo.

### Todo

- [ ] In the introduction
    - [ ] Add a paragraph why it makes sense to use FDP in the context of databases
- [ ] Write the Results section
    - [ ] Add a smooth introduction section to the implementation plan
- [ ] Create a small vocabulary table with the different Acronyms
- [ ] Describe in Background
   - [ ] What an regular SSD is
       - [ ] What is write amplification?
       - [ ] When does it happen?
       - [ ] Why does it matter?
 - [ ] Add specific version of kernels needed
 - [ ] In Impl. plan
     - [ ] Expand the explanation of subsystems
